# Numpy的array合并

In [1]:
import numpy as np

In [2]:
A = np.array([1,1,1])
B = np.array([2,2,2])

## 将两个array上下合并(vertical stack) 

In [4]:
print(np.vstack((A,B)))

[[1 1 1]
 [2 2 2]]


In [5]:
C = np.vstack((A,B))
print(A.shape,C.shape)

(3,) (2, 3)


A只是一个序列，而对于C，它是A,B进行上下合并，所以就变为2行3列的矩阵

## 将两个矩阵左右合并(horizontal  stack) 

In [11]:
D = np.hstack((A,B))
print(D)
print(A.shape,D.shape)

[1 1 1 2 2 2]
(3,) (6,)


因为A和B都是一个序列，所以进行左右合并后还是一个序列

无法将一个序列进行转置，例如下面这种方法

In [7]:
print(A.T)

[1 1 1]


打印结果仍然是原序列

## 改变行的维度

In [9]:
C = A[np.newaxis,:]
print(C)
print(C.shape)

[[1 1 1]]
(1, 3)


以前的shape是(3,)，当把newaxis放在前面的时候变成了1×3，也就是前面的维数发生了变化，后面的维数发生了变化

## 改变列的维度 

In [10]:
D = A[:,np.newaxis]
print(D)
print(D.shape)

[[1]
 [1]
 [1]]
(3, 1)


而把newaxis放后面的时候，输出的shape是3×1，也就是后面增加了一个维数

**newaxis放在第几个位置，就会在shape里面看到相应的位置增加了一个维数**

## 将两个数列进行转置后合并 

In [13]:
A = np.array([1,1,1])[:,np.newaxis]
B = np.array([2,2,2])[:,np.newaxis]
D = np.hstack((A,B))
print(D)
print(A.shape,D.shape)

[[1 2]
 [1 2]
 [1 2]]
(3, 1) (3, 2)


## 补充一种另外的合并方式 

可以用axis来控制需要合并的方式

In [15]:
C = np.concatenate((A,B,B,A),axis=0)
print(C)

[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]


In [16]:
C = np.concatenate((A,B,B,A),axis=1)
print(C)

[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]
