# Numpy数组创建

先导包：

In [6]:
import numpy as np

## 创建数组
括号里面填入要创建的这个array的参数，通常是列表形式，打印的结果其实和列表没有什么差别，不过中间没有了**逗号**

In [7]:
a = np.array([1,2,3])
print(a)

[1 2 3]


## 定义array的类型

每一种array可以定义它的类型，在创建的时候可以指定它的类型，使用**dtype = np.数据类型**

In [8]:
a = np.array([1,2,3],dtype = np.int)
print(a.dtype)

int32


如果输入64位的int就是64位的int类型，int有int16，int32和int64三种类型

In [9]:
a = np.array([1,2,3],dtype = np.int64)
print(a.dtype)

int64


除了**int**之外，还有**float**类型，有float64和float32的类型

In [10]:
a = np.array([1,2,3],dtype = np.float64)
print(a.dtype)

a = np.array([1,2,3],dtype = np.float32)
print(a.dtype)

float64
float32


通常来说位数越小所占用的空间就越小，但如果想要更精确的话，就需要位数更大的类型

## 定义二维的array

类似于Python中定义二维列表的方法，在列表外面多加一层列表

In [11]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


生成全部为0的矩阵，括号里面填入该列表的行数和列数，**注意行数和列数要用( )或者用[ ]括起来**，在默认的情况下，zeros创建的数组元素类型是浮点型的，如果要使用其他类型，可以设置dtype参数进行声明

In [12]:
a = np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


生成全部为1的矩阵:

In [15]:
a = np.ones((3,4),dtype = np.int16)
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


使用方括号括行数和列数的示例：

In [16]:
a = np.zeros([3,4])
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


也可以生成无意义的数组：

In [17]:
a = np.empty((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## 生成有序的数列或矩阵：

In [19]:
a = np.arange(10,20,2) #类似于Python中的range
print(a)

[10 12 14 16 18]


## 改变数列的维度：
使用**reshape**函数

改变前的数列：

In [21]:
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


改变后的数列：

In [22]:
a = np.arange(12).reshape((3,4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## 生成线段：
参数(a,b,c)表示将a到b分为c-1段

In [24]:
a = np.linspace(1,10,5)
print(a)

[ 1.    3.25  5.5   7.75 10.  ]


同样，线段也可以更改它的shape

In [25]:
a = np.linspace(1,10,6).reshape((2,3))
print(a)

[[ 1.   2.8  4.6]
 [ 6.4  8.2 10. ]]
