# Numpy的索引

In [1]:
import numpy as np

In [2]:
A = np.arange(3,15)
print(A)

[ 3  4  5  6  7  8  9 10 11 12 13 14]


## 获取某一位置的元素 

In [3]:
print(A[3])

6


In [4]:
A = np.arange(3,15).reshape((3,4))
print(A)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


## 在二维数组中的索引 

## 索引某一行元素 

In [5]:
print(A[2])

[11 12 13 14]


## 索引某一个元素 

In [6]:
print(A[1][1])

8


也可以用下面这种方式索引某一个元素

In [7]:
print(A[1,1])

8


## 打印某一行的所有数 

In [8]:
print(A[2,:])

[11 12 13 14]


## 打印某一列的所有数 

In [10]:
print(A[:,1])

[ 4  8 12]


## 打印某一行指定的连续列的数字 

In [12]:
print(A[1,1:3])

[8 9]


## 打印每一行的数 

In [13]:
for row in A:
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


## 打印每一列的数 

Numpy的array中没有这样的迭代，但是可以通过**矩阵的转置**来实现
迭代转置后的行其实就是迭代转置前的列

In [14]:
for column in A.T:
    print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


## 打印每一个元素 

In [15]:
print(A.flatten())
for item in A.flat:
    print(item)

[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14
