# Numpy的基础运算1 


先创建两个数列

In [30]:
import numpy as np
a = np.array([10,20,30,40])
b = np.arange(4)
print(a,b)

[10 20 30 40] [0 1 2 3]


## array的加减法

In [31]:
c = a-b
print(c)
c = a+b
print(c)

[10 19 28 37]
[10 21 32 43]


## 矩阵的n次方

In [32]:
b = np.arange(4)
print(b)
c = b**2
print(c)

[0 1 2 3]
[0 1 4 9]


## 三角函数的运算

对a的每一个值求sin值：

In [33]:
a = np.array([10,20,30,40])
c = 10*np.sin(a)
print(c)

[-5.44021111  9.12945251 -9.88031624  7.4511316 ]


对a的每一个值求cos值：

In [34]:
c = 10*np.cos(a)
print(c)

[-8.39071529  4.08082062  1.5425145  -6.66938062]


对a的每一个值求tan值：

In [35]:
c = 10*np.tan(a)
print(c)

[  6.48360827  22.37160944 -64.05331197 -11.17214931]


## 判断array中有多少个值小于某个数

In [36]:
b = np.arange(4)
print(b<3)

[ True  True  True False]


每个位置满足条件时打印True，否则打印False

## 矩阵的运算 

In [37]:
a = np.array([[1,1],
             [0,1]])
b = np.arange(4).reshape((2,2))
print(a)
print(b)

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]


### 将两个矩阵中的值逐个相乘

In [38]:
c = a*b
print(c)

[[0 1]
 [0 3]]


### 矩阵的乘法

In [39]:
c_dot = np.dot(a,b)
print(c_dot)

[[2 4]
 [2 3]]


### 矩阵乘法的另一种写法

In [40]:
c_dot_2 = a.dot(b)
print(c_dot_2)

[[2 4]
 [2 3]]


## 随机产生矩阵

In [41]:
a = np.random.random((2,4))
print(a)

[[0.92771354 0.06070335 0.26261475 0.03275783]
 [0.52355648 0.89876902 0.86996505 0.11572835]]


## 求矩阵中所有元素的最大值 

In [42]:
print(np.max(a))

0.9277135412087887


## 求矩阵中所有元素的最小值 

In [43]:
print(np.min(a))

0.03275782590941312


## 求矩阵中所有元素的和 

In [44]:
print(np.sum(a))

3.6918083642632227


## 对矩阵的每一行求和

In [45]:
print(np.sum(a,axis=1))
print(a.sum(axis=1))

[1.28378946 2.4080189 ]
[1.28378946 2.4080189 ]


## 对矩阵的每一列求和 

In [46]:
print(np.sum(a,axis=0))
print(a.sum(axis=0))

[1.45127002 0.95947237 1.1325798  0.14848618]
[1.45127002 0.95947237 1.1325798  0.14848618]


## 求矩阵每一行的最小值 

In [47]:
print(np.min(a,axis=1))
print(a.min(axis=1))

[0.03275783 0.11572835]
[0.03275783 0.11572835]


## 求矩阵每一列的最小值 

In [48]:
print(np.min(a,axis=0))
print(a.min(axis=0))

[0.52355648 0.06070335 0.26261475 0.03275783]
[0.52355648 0.06070335 0.26261475 0.03275783]


## 求矩阵每一行的最大值 

In [49]:
print(np.max(a,axis=1))
print(a.max(axis=1))

[0.92771354 0.89876902]
[0.92771354 0.89876902]


## 求矩阵每一列的最大值

In [50]:
print(np.max(a,axis=0))
print(a.max(axis=0))

[0.92771354 0.89876902 0.86996505 0.11572835]
[0.92771354 0.89876902 0.86996505 0.11572835]
