# Numpy的copy与deep copy

In [1]:
import numpy as np

In [2]:
a = np.arange(4)
print(a)

[0 1 2 3]


In [3]:
b = a
c = a
d = b
print(b,c,d)

[0 1 2 3] [0 1 2 3] [0 1 2 3]


如果修改a中第0位元素

In [4]:
a[0] = 11
print(a)

[11  1  2  3]


In [5]:
print(b,c,d)

[11  1  2  3] [11  1  2  3] [11  1  2  3]


发现b,c,d中的第0位元素也都被改变了

In [6]:
b is a 

True

In [7]:
c is a

True

In [8]:
d is a

True

通过以上三次输出结果发现在Numpy array中通过上面的赋值，其实a,b,c,d都是同一个对象，上面的复制其实也就是**浅复制**

同样地，假设现在修改d的值

In [9]:
d[1:3] = [22,33]
print(d)

[11 22 33  3]


In [10]:
print(a)

[11 22 33  3]


而a的值也同样被修改了

## 深度复制

就是指将被复制对象完全再复制一遍作为独立的新个体单独存在。所以在改变原有被复制对象时，不会对已经复制出来的新对象产生影响。 

In [11]:
b = a.copy() #deep copy
print(b)

[11 22 33  3]


In [13]:
a[3] = 44
print(b)

[11 22 33  3]


In [14]:
print(a)

[11 22 33 44]


可以看到，a的值已经改变了，而b的值没有被改变